name: 'Run Build Checks'
description: 'Execute build, test, lint, and typecheck commands for multi-language projects'
inputs:
  runtime:
    description: 'Runtime type (js, python, go, rust)'
    required: true
  package_manager:
    description: 'Package manager for running commands'
    required: true
  working-directory:
    description: 'Working directory for build checks'
    required: false
    default: '.'

outputs:
  BUILD_STATUS:
    description: 'Build status (pass, fail, or skip)'
    value: ${{ steps.checks.outputs.BUILD_STATUS }}
  TESTS_STATUS:
    description: 'Tests status (pass, fail, or skip)'
    value: ${{ steps.checks.outputs.TESTS_STATUS }}
  LINT_STATUS:
    description: 'Lint status (pass, fail, or skip)'
    value: ${{ steps.checks.outputs.LINT_STATUS }}
  TYPECHECK_STATUS:
    description: 'Typecheck status (pass, fail, or skip)'
    value: ${{ steps.checks.outputs.TYPECHECK_STATUS }}
  results_file:
    description: 'Path to combined results file'
    value: '/tmp/build-results/all.txt'

runs:
  using: 'composite'
  steps:
    - name: Run build checks
      id: checks
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        mkdir -p /tmp/build-results

        # Initialize statuses
        BUILD_STATUS="skip"
        TESTS_STATUS="skip"
        LINT_STATUS="skip"
        TYPECHECK_STATUS="skip"

        # Run build
        echo "=== Running build ===" > /tmp/build-results/build.txt
        case "${{ inputs.runtime }}" in
          js)
            if [ -f "package.json" ] && grep -q '"build"' package.json; then
              if ${{ inputs.package_manager }} run build >> /tmp/build-results/build.txt 2>&1; then
                BUILD_STATUS="pass"
              else
                BUILD_STATUS="fail"
              fi
            else
              echo "No build script found" >> /tmp/build-results/build.txt
            fi
            ;;
          python)
            if [ -f "setup.py" ] || ([ -f "pyproject.toml" ] && grep -q '\[build-system\]' pyproject.toml); then
              if python -m build >> /tmp/build-results/build.txt 2>&1; then
                BUILD_STATUS="pass"
              else
                BUILD_STATUS="fail"
              fi
            else
              echo "No build system found" >> /tmp/build-results/build.txt
            fi
            ;;
          go)
            if go build ./... >> /tmp/build-results/build.txt 2>&1; then
              BUILD_STATUS="pass"
            else
              BUILD_STATUS="fail"
            fi
            ;;
          rust)
            if cargo build >> /tmp/build-results/build.txt 2>&1; then
              BUILD_STATUS="pass"
            else
              BUILD_STATUS="fail"
            fi
            ;;
        esac
        echo "BUILD_STATUS=$BUILD_STATUS" >> $GITHUB_OUTPUT

        # Run tests
        echo "=== Running tests ===" > /tmp/build-results/tests.txt
        case "${{ inputs.runtime }}" in
          js)
            if [ -f "package.json" ] && grep -q '"test"' package.json; then
              if ${{ inputs.package_manager }} test >> /tmp/build-results/tests.txt 2>&1; then
                TESTS_STATUS="pass"
              else
                TESTS_STATUS="fail"
              fi
            else
              echo "No test script found" >> /tmp/build-results/tests.txt
            fi
            ;;
          python)
            if command -v pytest >/dev/null 2>&1; then
              if pytest >> /tmp/build-results/tests.txt 2>&1; then
                TESTS_STATUS="pass"
              else
                TESTS_STATUS="fail"
              fi
            else
              echo "pytest not found" >> /tmp/build-results/tests.txt
            fi
            ;;
          go)
            if go test ./... >> /tmp/build-results/tests.txt 2>&1; then
              TESTS_STATUS="pass"
            else
              TESTS_STATUS="fail"
            fi
            ;;
          rust)
            if cargo test >> /tmp/build-results/tests.txt 2>&1; then
              TESTS_STATUS="pass"
            else
              TESTS_STATUS="fail"
            fi
            ;;
        esac
        echo "TESTS_STATUS=$TESTS_STATUS" >> $GITHUB_OUTPUT

        # Run lint
        echo "=== Running lint ===" > /tmp/build-results/lint.txt
        case "${{ inputs.runtime }}" in
          js)
            if [ -f "package.json" ] && grep -q '"lint"' package.json; then
              if ${{ inputs.package_manager }} run lint >> /tmp/build-results/lint.txt 2>&1; then
                LINT_STATUS="pass"
              else
                LINT_STATUS="fail"
              fi
            else
              echo "No lint script found" >> /tmp/build-results/lint.txt
            fi
            ;;
          python)
            if command -v ruff >/dev/null 2>&1; then
              if ruff check . >> /tmp/build-results/lint.txt 2>&1; then
                LINT_STATUS="pass"
              else
                LINT_STATUS="fail"
              fi
            else
              echo "ruff not found" >> /tmp/build-results/lint.txt
            fi
            ;;
          go)
            if command -v golint >/dev/null 2>&1; then
              if golint ./... >> /tmp/build-results/lint.txt 2>&1; then
                LINT_STATUS="pass"
              else
                LINT_STATUS="fail"
              fi
            else
              echo "golint not found" >> /tmp/build-results/lint.txt
            fi
            ;;
          rust)
            if cargo clippy >> /tmp/build-results/lint.txt 2>&1; then
              LINT_STATUS="pass"
            else
              LINT_STATUS="fail"
            fi
            ;;
        esac
        echo "LINT_STATUS=$LINT_STATUS" >> $GITHUB_OUTPUT

        # Run typecheck
        echo "=== Running typecheck ===" > /tmp/build-results/typecheck.txt
        case "${{ inputs.runtime }}" in
          js)
            if [ -f "tsconfig.json" ]; then
              if npx tsc --noEmit >> /tmp/build-results/typecheck.txt 2>&1; then
                TYPECHECK_STATUS="pass"
              else
                TYPECHECK_STATUS="fail"
              fi
            else
              echo "No tsconfig.json found" >> /tmp/build-results/typecheck.txt
            fi
            ;;
          python)
            if command -v mypy >/dev/null 2>&1; then
              if mypy . >> /tmp/build-results/typecheck.txt 2>&1; then
                TYPECHECK_STATUS="pass"
              else
                TYPECHECK_STATUS="fail"
              fi
            else
              echo "mypy not found" >> /tmp/build-results/typecheck.txt
            fi
            ;;
          *)
            echo "Typecheck not applicable for ${{ inputs.runtime }}" >> /tmp/build-results/typecheck.txt
            ;;
        esac
        echo "TYPECHECK_STATUS=$TYPECHECK_STATUS" >> $GITHUB_OUTPUT

        # Combine all results
        cat /tmp/build-results/*.txt > /tmp/build-results/all.txt
        echo "Build: $BUILD_STATUS"
        echo "Tests: $TESTS_STATUS"
        echo "Lint: $LINT_STATUS"
        echo "TypeCheck: $TYPECHECK_STATUS"
