name: 'Setup OpenCode Environment'
description: 'Install Bun, OpenCode CLI, project dependencies, and ast-grep'
inputs:
  bun-version:
    description: 'Bun version to install'
    required: false
    default: 'latest'
  install-ast-grep:
    description: 'Whether to install ast-grep CLI'
    required: false
    default: 'true'
  working-directory:
    description: 'Working directory for dependency installation'
    required: false
    default: '.'
outputs:
  bun-version:
    description: 'Version of Bun that was installed'
    value: ${{ steps.setup-bun.outputs.bun-version }}

runs:
  using: 'composite'
  steps:
    - name: Setup Bun
      id: setup-bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ inputs.bun-version }}

    - name: Install OpenCode CLI
      shell: bash
      run: |
        echo "Installing OpenCode CLI..."
        bun install -g opencode-ai@latest
        echo "OpenCode CLI installed: $(opencode --version || echo 'version check not supported')"

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: bun install

    - name: Install ast-grep
      if: inputs.install-ast-grep == 'true'
      shell: bash
      run: |
        bun install -g @ast-grep/cli
        bun pm -g trust @ast-grep/cli
        ast-grep --version
